# Generated by Django 3.1.3 on 2020-11-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
